
@interface FrontPageController : TMViewController <TMFrontPageElementEventDelegate, TMFrontPageLayoutDelegate, TMFrontPageLayoutScrollDelegate, TMFrontPageLayoutDataSource, TMFrontPageLayoutPageScrollDelegate, TMMuiScrollViewDelegate, TMMuiLazyScrollViewDataSource, TMMuiNoResultViewDelegate, FlashManagerDelegate, UITextFieldDelegate, UIToolbarDelegate> {
	BOOL _loading;
	BOOL _loadingMore;
	BOOL _canBeRecycled;
	BOOL _fromCache;
	BOOL _hasMoreData;
	BOOL _autoShowSuperBrandMask;
	BOOL _moreRecommendNumSaved;
	BOOL _trackingPerformance;
	BOOL _clearCache;
	BOOL _mainVenueShoudShow;
	BOOL _popLayerShow;
	BOOL _isBack;
	BOOL _seaviewHasNoMore;
	BOOL _elevatorShow;
	BOOL _isNewExposure;
	BOOL _isSaleExposure;
	BOOL _isHotExposure;
	BOOL _goodShopShow;
	BOOL _recommendHallShow;
	BOOL _recommendVVipShow;
	BOOL _isNotFirstLoad;
	NSArray* _dataSource;
	NSMutableDictionary* _layoutModelDict;
	NSMutableDictionary* _layoutDict;
	NSMutableArray* _layoutArray;
	TMFrontPageLazyScrollView* _contentView;
	SearchBoxButton* _searchBoxBtn;
	NSString* _currentLayout;
	NSMutableDictionary* _showedAlgIdDict;
	AirTrack* _tester;
	NSString* _pageName;
	NSString* _currentUserId;
	NSString* _bucketNumber;
	NSMutableDictionary* _taobaoNeededShowedParams;
	TMMuiMsgBadgeButton* _messageButton;
	TMFrontPageRequest* _staticDataRequest;
	TMFrontPageMoreRecommendRequest* _moreRecommendRequest;
	TMFrontPageGoodShopRequest* _goodShopRequest;
	TMFrontPageLayout* _moreDataLayout;
	NSDate* _lastUpdateDate;
	NSMutableDictionary* _elementDict;
	TMMuiNoResultView* _errorTips;
	FrontPageTopBar* _topBar;
	FrontPageTopTips* _frontPageTopTips;
	FrontPageBottomTips* _frontPageBottomTips;
	UIImageView* _flashView;
	TMMuiButton* _returnToTopBtn;
	TMFrontPageElement* _superAView;
	TMFrontPageElementModel* _superAModel;
	TMFrontPageLayout* _superALayout;
	NSDictionary* _flashInfo;
	NSMutableArray* _uploadedKeyword;
	NSDictionary* _toUploadMoreRecommendParams;
	UITextField* _dateField;
	TMFrontPageTimePickerView* _timePicker;
	UIToolbar* _timePickerBar;
	int _recommendPageCount;
	NSMutableArray* _showedLayouts;
	UIControl* _blockControl;
	UIView* _mainVenueView;
	float _mainVenueBottom;
	NSString* _shakeUrl;
	NSString* _shakeTitle;
	NSMutableArray* _seaviewRooms;
	NSMutableArray* _seaviewKeyFrames;
	ElevatorView* _elevatorView;
	NSString* _topBarChangeColor;
	NSMutableArray* _popLayerTimerRemindArray;
	NSString* _popLayerTimerTipText;
	NSDictionary* _mainVenue;
	NSString* _jumpParam;
	double _lastContentY;
	double _topBarChangeStartTime;
	double _topBarChangeEndTime;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSString* jumpParam;
@property(assign, nonatomic) BOOL isNotFirstLoad;
@property(retain, nonatomic) NSDictionary* mainVenue;
@property(retain, nonatomic) NSString* popLayerTimerTipText;
@property(retain, nonatomic) NSMutableArray* popLayerTimerRemindArray;
@property(retain, nonatomic) NSString* topBarChangeColor;
@property(assign, nonatomic) double topBarChangeEndTime;
@property(assign, nonatomic) double topBarChangeStartTime;
@property(assign, nonatomic) BOOL recommendVVipShow;
@property(assign, nonatomic) BOOL recommendHallShow;
@property(assign, nonatomic) BOOL goodShopShow;
@property(assign, nonatomic) BOOL isHotExposure;
@property(assign, nonatomic) BOOL isSaleExposure;
@property(assign, nonatomic) BOOL isNewExposure;
@property(assign, nonatomic) BOOL elevatorShow;
@property(assign, nonatomic) BOOL seaviewHasNoMore;
@property(retain, nonatomic) ElevatorView* elevatorView;
@property(retain, nonatomic) NSMutableArray* seaviewKeyFrames;
@property(retain, nonatomic) NSMutableArray* seaviewRooms;
@property(assign, nonatomic) BOOL isBack;
@property(copy, nonatomic) NSString* shakeTitle;
@property(copy, nonatomic) NSString* shakeUrl;
@property(assign, nonatomic) BOOL popLayerShow;
@property(assign, nonatomic) float mainVenueBottom;
@property(retain, nonatomic) UIView* mainVenueView;
@property(assign, nonatomic) BOOL mainVenueShoudShow;
@property(retain, nonatomic) UIControl* blockControl;
@property(assign, nonatomic) BOOL clearCache;
@property(retain, nonatomic) NSMutableArray* showedLayouts;
@property(assign, nonatomic) int recommendPageCount;
@property(assign, nonatomic, getter=isTrackingPerformance) BOOL trackingPerformance;
@property(retain, nonatomic) UIToolbar* timePickerBar;
@property(retain, nonatomic) TMFrontPageTimePickerView* timePicker;
@property(retain, nonatomic) UITextField* dateField;
@property(retain, nonatomic) NSDictionary* toUploadMoreRecommendParams;
@property(assign, nonatomic) BOOL moreRecommendNumSaved;
@property(retain, nonatomic) NSMutableArray* uploadedKeyword;
@property(retain, nonatomic) NSDictionary* flashInfo;
@property(retain, nonatomic) TMFrontPageLayout* superALayout;
@property(retain, nonatomic) TMFrontPageElementModel* superAModel;
@property(retain, nonatomic) TMFrontPageElement* superAView;
@property(retain, nonatomic) TMMuiButton* returnToTopBtn;
@property(assign, nonatomic) double lastContentY;
@property(assign, nonatomic) BOOL autoShowSuperBrandMask;
@property(retain, nonatomic) UIImageView* flashView;
@property(retain, nonatomic) FrontPageBottomTips* frontPageBottomTips;
@property(retain, nonatomic) FrontPageTopTips* frontPageTopTips;
@property(retain, nonatomic) FrontPageTopBar* topBar;
@property(retain, nonatomic) TMMuiNoResultView* errorTips;
@property(retain, nonatomic) NSMutableDictionary* elementDict;
@property(retain, nonatomic) NSDate* lastUpdateDate;
@property(retain, nonatomic) TMFrontPageLayout* moreDataLayout;
@property(assign, nonatomic) BOOL hasMoreData;
@property(retain, nonatomic) TMFrontPageGoodShopRequest* goodShopRequest;
@property(retain, nonatomic) TMFrontPageMoreRecommendRequest* moreRecommendRequest;
@property(retain, nonatomic) TMFrontPageRequest* staticDataRequest;
@property(assign, nonatomic) __weak TMMuiMsgBadgeButton* messageButton;
@property(retain, nonatomic) NSMutableDictionary* taobaoNeededShowedParams;
@property(assign) BOOL fromCache;
@property(assign) BOOL canBeRecycled;
@property(retain, nonatomic) NSString* bucketNumber;
@property(retain, nonatomic) NSString* currentUserId;
@property(retain, nonatomic) NSString* pageName;
@property(retain, nonatomic) AirTrack* tester;
@property(retain, nonatomic) NSMutableDictionary* showedAlgIdDict;
@property(assign, nonatomic, getter=isLoadingMore) BOOL loadingMore;
@property(assign, nonatomic, getter=isLoading) BOOL loading;
@property(retain, nonatomic) NSString* currentLayout;
@property(retain, nonatomic) SearchBoxButton* searchBoxBtn;
@property(retain, nonatomic) TMFrontPageLazyScrollView* contentView;
@property(retain, nonatomic) NSMutableArray* layoutArray;
@property(retain, nonatomic) NSMutableDictionary* layoutDict;
@property(retain, nonatomic) NSMutableDictionary* layoutModelDict;
@property(retain, nonatomic) NSArray* dataSource;
-(void).cxx_destruct;
-(void)removeBlockControlAndResignDateField;
-(void)textFieldDidBeginEditing:(id)textField;
-(void)tabBarReclick:(id)reclick;
-(void)clickOKButton;
-(void)clickClearButton;
-(void)clickCancleButton;
-(BOOL)useShakeForMiaoshaBaitItems;
-(void)dealloc;
-(void)didReceiveMemoryWarning;
-(void)viewDidDisappear:(BOOL)view;
-(void)setRewritedActionURL:(id)url;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(void)loadView;
-(id)init;
-(void)frontPageConfigUpdate;
-(void)popLayerUpdate;
-(void)mainVenueCheck;
-(void)returnToTopBtnShow;
-(void)elevatorViewShowWithOffsetY;
-(void)makeFrontPageStyleNavigationBar;
-(void)handleThemeUpdate;
-(void)handleThemeUpdateNotification:(id)notification;
-(void)resetContent;
-(void)calculateLayoutFrame:(id)frame;
-(void)layoutContentWithLayoutCalculate:(BOOL)layoutCalculate;
-(void)reLayoutContent;
-(void)initNavigationItem;
-(void)initContentFromCache:(BOOL)cache;
-(void)initSearchBox;
-(id)historyCeleBrandIds;
-(void)saveHistoryCeleBrandIdForModel:(id)model;
-(id)historyBrandIDs;
-(void)saveHistoryBrandIdForModel:(id)model;
-(void)saveMoreRecommendVisibleNum;
-(int)moreRecommendVisibleNum;
-(id)historyItemIDs;
-(void)appendLayout:(id)layout;
-(void)loadData;
-(void)loadMore;
-(id)UTPageName;
-(void)cleanViewController;
-(void)refreshMessageCount;
-(void)appendElementModels:(id)models models:(id)models2;
-(void)buildAllElementModels;
-(void)postLayoutDoneNotification;
-(void)uploadMoreRecommendShowWithParams:(id)params;
-(void)enterForeground;
-(void)stopPullAnimation;
-(void)buildDateField;
-(void)endTrackRenderPerformance;
-(void)renderWithDataString:(id)dataString fromCache:(BOOL)cache;
-(void)renderWithDataFromCache:(BOOL)cache;
-(void)updateModuleShowedStatusForLayout:(id)layout;
-(void)mainViewHidden:(BOOL)hidden;
-(void)mainVenueViewClick;
-(void)btnListClick:(id)click;
-(void)btnScanClick:(id)click;
-(void)btnMessageClick:(id)click;
-(void)btnSearchBoxClick:(id)click;
-(double)timeIntervalForString:(id)string;
-(id)customDataKey;
-(id)scrollView:(id)view itemByMuiID:(id)anId;
-(id)scrollView:(id)view rectModelAtIndex:(unsigned)index;
-(unsigned)numberOfItemInScrollView:(id)scrollView;
-(void)element:(id)element clickedWithAction:(id)action userInfo:(id)info;
-(void)deleteElement:(id)element;
-(void)pageLayoutJumpMorePage:(id)page;
-(void)pageLayout:(id)layout atIndex:(unsigned)index;
-(void)layout:(id)layout atIndex:(unsigned)index;
-(void)layout:(id)layout heightChanged:(BOOL)changed;
-(unsigned)numberOfElementsOfLayout:(id)layout;
-(id)elementForLayout:(id)layout byMuiID:(id)anId;
-(void)triggeredLoadData:(unsigned)data;
-(void)scrollViewDidScroll:(id)scrollView;
-(void)processBeforePush:(id)push withContext:(id)context;
-(void)didTouchDownButton:(id)button;
-(void)flashViewWillDisappear;
-(void)flashViewDidShowWithData:(id)flashView;
-(void)shakeDeInit;
-(void)shakeInit;
-(BOOL)_shakeCheckEnable;
-(double)_shakeConvertTimeinterval:(id)timeinterval;
-(void)_shakeDelayJump:(id)jump;
-(void)appActive;
-(void)appResign;
@end


@interface TMFrontPageLazyScrollView : TMMuiLazyScrollView {
}
@end

@interface TMFrontPageElementModelGoodShop : TMFrontPageElementModel {
	NSString* _logoURL;
	NSString* _tagImgURL;
	NSString* _desc;
	NSString* _img1URL;
	NSString* _img2URL;
	NSString* _img3URL;
}
@property(retain, nonatomic) NSString* img3URL;
@property(retain, nonatomic) NSString* img2URL;
@property(retain, nonatomic) NSString* img1URL;
@property(retain, nonatomic) NSString* desc;
@property(retain, nonatomic) NSString* tagImgURL;
@property(retain, nonatomic) NSString* logoURL;
-(void).cxx_destruct;
-(void)calculateHeight;
-(id)initWithDictionary:(id)dictionary;
@end

@interface TMFrontPageElementNewHot : TMFrontPageElement {
	unsigned _type;
	NSString* _imageA;
	NSString* _imageB;
	NSString* _imageC;
	NSString* _imageD;
	NSString* _thisType;
	TMImageView* _imageViewA;
	TMImageView* _imageViewB;
	TMImageView* _imageViewC;
	TMImageView* _imageViewD;
	UIImageView* _typeImageVew;
	UIImageView* _bgImageView;
	UIView* _bgColorView;
	UILabel* _titleLabel;
	UILabel* _subTitleLabel;
}
@property(retain, nonatomic) UILabel* subTitleLabel;
@property(retain, nonatomic) UILabel* titleLabel;
@property(retain, nonatomic) UIView* bgColorView;
@property(retain, nonatomic) UIImageView* bgImageView;
@property(retain, nonatomic) UIImageView* typeImageVew;
@property(retain, nonatomic) TMImageView* imageViewD;
@property(retain, nonatomic) TMImageView* imageViewC;
@property(retain, nonatomic) TMImageView* imageViewB;
@property(retain, nonatomic) TMImageView* imageViewA;
@property(retain, nonatomic) NSString* thisType;
@property(retain, nonatomic) NSString* imageD;
@property(retain, nonatomic) NSString* imageC;
@property(retain, nonatomic) NSString* imageB;
@property(retain, nonatomic) NSString* imageA;
-(unsigned)type;
-(void).cxx_destruct;
-(void)calculateLayout;
-(id)initWithIdentifier:(id)identifier;
@end


@interface TMFrontPageLayoutModel : XXUnknownSuperclass {
	NSArray* _margin;
	NSString* _identifier;
	unsigned _type;
	NSString* _bgColor;
	NSString* _loadApi;
	unsigned _keyIndex;
	NSArray* _items;
	NSString* _algId;
	NSDictionary* _ctrClickParam;
	NSArray* _ctrClickParamArray;
	NSString* _ctrClickName;
	NSArray* _cols;
	NSString* _forLabel;
}
@property(retain, nonatomic) NSString* forLabel;
@property(retain, nonatomic) NSArray* cols;
@property(retain, nonatomic) NSString* ctrClickName;
@property(retain, nonatomic) NSArray* ctrClickParamArray;
@property(retain, nonatomic) NSDictionary* ctrClickParam;
@property(retain, nonatomic) NSString* algId;
@property(retain, nonatomic) NSArray* items;
@property(assign, nonatomic) unsigned keyIndex;
@property(retain, nonatomic) NSArray* margin;
@property(retain, nonatomic) NSString* loadApi;
@property(retain, nonatomic) NSString* bgColor;
@property(assign, nonatomic) unsigned type;
@property(retain, nonatomic) NSString* identifier;
-(void).cxx_destruct;
-(unsigned)numberOfColumns;
-(float)marginLeft;
-(float)marginBottom;
-(float)marginRight;
-(float)marginTop;
-(CGRect)originalRectConversionToAbsRect:(CGRect)absRect withModifiedViewRect:(CGRect)modifiedViewRect;
-(id)initWithDictionary:(id)dictionary;
@end


@interface TMFrontPageElementModel : XXUnknownSuperclass <TMFrontPageElementCalculateHeightDelegate> {
	BOOL _pin;
	BOOL _canReuse;
	BOOL _noReset;
	BOOL _isExposure;
	BOOL _animFlag;
	NSArray* _margin;
	unsigned _elementIndex;
	NSString* _identifier;
	NSString* _syncIds;
	unsigned _type;
	NSString* _bgColor;
	NSString* _display;
	NSString* _title;
	NSString* _titleColor;
	NSString* _subTitle;
	NSString* _subTitleColor;
	NSString* _imgUrl;
	NSString* _action;
	NSString* _celeBrandId;
	NSArray* _appendVarKeys;
	float _baseHeight;
	NSString* _source;
	NSDictionary* _pageParams;
	NSString* _pageParamsString;
	NSString* _reuseIdentifier;
	NSString* _muiID;
	NSDictionary* _ctrClickParam;
	NSString* _ctrClickParamString;
	CGRect _rect;
	CGRect _absRect;
	CGRect _parentRect;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) BOOL animFlag;
@property(assign, nonatomic) BOOL isExposure;
@property(retain, nonatomic) NSString* ctrClickParamString;
@property(retain, nonatomic) NSDictionary* ctrClickParam;
@property(assign, nonatomic) BOOL noReset;
@property(assign, nonatomic) BOOL canReuse;
@property(retain, nonatomic) NSString* muiID;
@property(retain, nonatomic) NSString* reuseIdentifier;
@property(assign, nonatomic) CGRect parentRect;
@property(assign, nonatomic) CGRect absRect;
@property(assign, nonatomic) CGRect rect;
@property(retain, nonatomic) NSString* pageParamsString;
@property(retain, nonatomic) NSDictionary* pageParams;
@property(retain, nonatomic) NSString* source;
@property(assign, nonatomic) float baseHeight;
@property(retain, nonatomic) NSArray* appendVarKeys;
@property(assign, nonatomic) BOOL pin;
@property(retain, nonatomic) NSString* celeBrandId;
@property(retain, nonatomic) NSString* action;
@property(retain, nonatomic) NSString* imgUrl;
@property(retain, nonatomic) NSString* subTitleColor;
@property(retain, nonatomic) NSString* subTitle;
@property(retain, nonatomic) NSString* titleColor;
@property(retain, nonatomic) NSString* title;
@property(retain, nonatomic) NSArray* margin;
@property(retain, nonatomic) NSString* display;
@property(retain, nonatomic) NSString* bgColor;
@property(assign, nonatomic) unsigned type;
@property(retain, nonatomic) NSString* syncIds;
@property(retain, nonatomic) NSString* identifier;
@property(assign, nonatomic) unsigned elementIndex;
-(void).cxx_destruct;
-(void)right:(float)right FromModel:(id)model;
-(void)left:(float)left FromModel:(id)model;
-(void)bottom:(float)bottom FromModel:(id)model;
-(void)top:(float)top FromModel:(id)model;
-(void)rightInContainer:(float)container shouldResize:(BOOL)resize;
-(void)leftInContainer:(float)container shouldResize:(BOOL)resize;
-(void)bottomInContainer:(float)container shouldResize:(BOOL)resize;
-(void)topInContainer:(float)container shouldResize:(BOOL)resize;
-(float)marginLeft;
-(float)marginBottom;
-(float)marginRight;
-(float)marginTop;
-(void)calculateHeight;
-(id)initWithDictionary:(id)dictionary;
@end
